std::string muffins = 
"+------------------------------------------------------------------------------+"
"|  This game was made and programmed by Steven Weiss. Isn't it amazing? Like,  |"
"|  seriously, how awesome is this thing? Amiright? Anyway, it's pretty crappy  |"
"|  in its current state, but hey, who cares?! Here's a hint, it's not me. So,  |"
"|  yeah. I guess a shoutout to my friend Josh, who's pretty cool and all. Also |"
"|  a shoutout to the dude who made and programmed this, Steven Weiss. He's     |"
"|  actually the guy who made and programmed this! Isn't it amazing? Like,      |"
"|  seriously, how awesome is this thing? Amiright? Anyway, it's pretty crappy  |"
"|  in its current state, but hey, who cares?! Here's a hint, it's not me. So,  |"
"|  yeah. I guess a shoutout to my friend Josh, who's pretty cool and all. Also |"
"|  a shoutout to the dude who made and programmed this, Steven Weiss. He's     |"
"|  actually the guy who made and programmed this! Isn't it amazing? Like,      |"
"|  seriously, how awesome is this thing? Amiright? Anyway, it's pretty crappy  |"
"|  in its current state, but hey, who cares?! Here's a hint, it's not me. So,  |"
"|  yeah. I guess a shoutout to my friend Josh, who's pretty cool and all. Also |"
"|  a shoutout to the dude who made and programmed this, Steven Weiss. He's     |"
"|  actually the guy who made and programmed this! Isn't it amazing? Like,      |"
"|  seriously, how awesome is this thing? Amiright? Anyway, it's pretty crappy  |"
"|  in its current state, but hey, who cares?! Here's a hint, it's not me. So,  |"
"|  yeah. I guess a shoutout to my friend Josh, who's pretty cool and all. Also |"
"|  a shoutout to the dude who made and programmed this, Steven Weiss. He's     |"
"|  actually the guy who made and programmed this! Isn't it amazing? Like,      |"
"|  seriously, how awesome is this thing? Amiright? Anyway, it's pretty crappy  |"
"|  in its current state, but hey, who cares?! Here's a hint, it's not me. So,  |"
"|  yeah. I guess a shoutout to my friend Josh, who's pretty cool and all. Also |"
"|  a shoutout to the dude who made and programmed this, Steven Weiss. He's     |"
"|  actually the guy who made and programmed this! Isn't it amazing? Like,      |"
"|  seriously, how awesome is this thing? Amiright? Anyway, it's pretty crappy  |"
"|  in its current state, but hey, who cares?! Here's a hint, it's not me. So,  |"
"|  yeah. I guess a shoutout to my friend Josh, who's pretty cool and all. Also |"
"|  a shoutout to the dude who made and programmed this, Steven Weiss. He's     |"
"|  actually the guy who made and programmed this! Isn't it amazing? Like,      |"
"|  seriously, how awesome is this thing? Amiright? Anyway, it's pretty crappy  |"
"|  in its current state, but hey, who cares?! Here's a hint, it's not me. So,  |"
"|  yeah. I guess a shoutout to my friend Josh, who's pretty cool and all. Also |"
"|  a shoutout to the dude who made and programmed this, Steven Weiss. He's     |"
"|  actually the guy who made and programmed this! Isn't it amazing? Like,      |"
"|  seriously, how awesome is this thing? Amiright? Anyway, it's pretty crappy  |"
"|  in its current state, but hey, who cares?! A hint: it's not me. So, yeah.   |"
"+------------------------------------------------------------------------------+";